args:
  base_lr: 0.0144
  batch_size: 16
  dataset: SMC2021
  deterministic: 1
  img_size: 224
  max_epochs: 10
  max_iterations: 2000
  n_classes: 15
  n_gpu: 1
  n_skip: 3
  root_path: A:\Datasets\SMC 2021 Std
  seed: 1234
  vit_name: R50-ViT-B_16
  vit_patches_size: 16
vit_config: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
  _convert_dict: true
  _fields:
    activation: softmax
    classifier: seg
    decoder_channels: !!python/tuple
    - 256
    - 128
    - 64
    - 16
    hidden_size: 768
    n_classes: 15
    n_skip: 3
    patch_size: 16
    patches: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        grid: !!python/tuple
        - 14
        - 14
        size: !!python/tuple
        - 16
        - 16
      _locked: false
      _type_safe: true
    pretrained_path: ../model/vit_checkpoint/imagenet21k/R50+ViT-B_16.npz
    representation_size: null
    resnet: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        num_layers: !!python/tuple
        - 3
        - 4
        - 9
        width_factor: 1
      _locked: false
      _type_safe: true
    resnet_pretrained_path: null
    skip_channels:
    - 512
    - 256
    - 64
    - 0
    transformer: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        attention_dropout_rate: 0.0
        dropout_rate: 0.1
        mlp_dim: 3072
        num_heads: 12
        num_layers: 12
      _locked: false
      _type_safe: true
  _locked: false
  _type_safe: true
